package hr.uniri.molapi.model.enums;

public enum Descriptor {
    mol_amw,
    mol_exactmw,
    mol_logp,
    mol_tpsa,
    mol_labuteasa,
    mol_fractioncsp3,
    mol_hba,
    mol_hbd,
    mol_numatoms,
    mol_numheavyatoms,
    mol_numrotatablebonds,
    mol_numheteroatoms,
    mol_numrings,
    mol_numaromaticrings,
    mol_numaliphaticrings,
    mol_numsaturatedrings,
    mol_numaromaticheterocycles,
    mol_numaliphaticheterocycles,
    mol_numsaturatedheterocycles,
    mol_numaromaticcarbocycles,
    mol_numaliphaticcarbocycles,
    mol_numsaturatedcarbocycles,
    mol_numspiroatoms,
    mol_numbridgeheadatoms,
    mol_inchi,
    mol_inchikey
}
